<?php
declare(strict_types=1);

require_once __DIR__ . '/../includes/auth.php';
require_once __DIR__ . '/../config/database.php';

protectPage(1);

header('Content-Type: application/json');

try {
    $db = new Database();
    $conn = $db->connect();
    
    $userId = (int) ($_SESSION['user_id'] ?? 0);
    
    // Get visit count (handled by this user)
    $visitStmt = $conn->prepare('SELECT COUNT(*) as count FROM clinic_visits WHERE handled_by = ?');
    $visitStmt->execute([$userId]);
    $visitCount = $visitStmt->fetch(PDO::FETCH_ASSOC)['count'] ?? 0;
    
    // Get report count (generated by this user)
    $reportStmt = $conn->prepare('SELECT COUNT(*) as count FROM report_logs WHERE generated_by = ?');
    $reportStmt->execute([$userId]);
    $reportCount = $reportStmt->fetch(PDO::FETCH_ASSOC)['count'] ?? 0;
    
    echo json_encode([
        'success' => true,
        'visits' => (int) $visitCount,
        'reports' => (int) $reportCount
    ]);
} catch (Exception $e) {
    echo json_encode([
        'success' => false,
        'message' => 'Failed to load statistics'
    ]);
}
